### ISSUE TITLE
Do we need to check that $.cssHooks exists

### ISSUE THREAD

**Issue by tomgrohl** [brandonaaron/jquery-cssHooks#19] opened 2010-11-11 08:55 UTC
In the cssHooks I wrote I check that the browsers supports the feature to be used ( border radius, border image..), but I also check to see if $.cssHooks exists to avoid errors when trying to use it with older versions of jQuery.

Wasn't sure if this was needed though, any thoughts?

**Comment by louisremi** [comment] 2010-11-11 09:55
This test won't save much processing to the browser and with or without the test, the hook will simply not work. But it won't break anything.
So it's not really needed.

**Comment by tomgrohl** [comment] 2010-11-11 10:09
I thought that but a test I did gives me an error saying that cssHooks is undefined ( in firefox and chrome) and object expected ( in IE ). 

By the looks of it, it may be best to use them, that way it would avoid throwing any errors.

**Comment by louisremi** [comment] 2010-11-11 10:23
Oh, of course.
On the other hand this can be a good clue that something is wrong with the jQuery version...

**Comment by louisremi** [comment] 2010-11-11 10:24
Instead of failing silently you will see that cssHooks is missing somewhere, I mean.

**Comment by tomgrohl** [comment] 2010-11-11 11:06
Ah ok. Maybe a check is need before hand then. Something like:

if( !$.cssHooks )
{
    $.error("The version of jQuery you are using doesn't support cssHooks");
}

Might be good to have in.

**Comment by pdokas** [comment] 2010-11-15 18:03
To prevent the error of assigning to a property of undefined I'd say that yeah, the check should be performed.

**Comment by louisremi** [comment] 2011-04-21 10:37
It is not a common practice to do this kind of things in jQuery plugins.
You should rather indicate in the source code of your file that the plugin depends on jQuery 1.4.3+, see skeleton.js for an example: https://github.com/brandonaaron/jquery-cssHooks/blob/master/skeleton.js

An error will be thrown anyway if jQuery.cssHooks is not defined, and it should not take long for the developer to find out what the problem is.

**Closed as completed by louisremi** 2011-04-21 10:37 UTC

**Comment by tomgrohl** [comment] 2011-04-21 12:20
Yeah your right. Developers would be used to seeing that kind of error so they should be able to find out what the problem is with ease.

I'll update my cssHooks and remove this check and add comments.
